client_config_backend: settings
client_config:
  client_id: 1033399706642-rkvvgpkf7a9elup0u4srk42n3crjdnic.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install